name: "Push Ffmpeg"
on:
  workflow_dispatch:

jobs:
  Building:
      runs-on: ubuntu-latest
      name: "Build and Push Ffmpeg Build"
      
      steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Login to DockerHub
        uses: docker/login-action@v1.14.1
        with:
          username: gufzer
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push images to Docker hub
        uses: docker/build-push-action@v2.9.0
        with:
          push: true
          platforms: linux/amd64
          tags: gufzer/ffmpeg:latest
